name: ebooks
version: 1.0.0+1
publish_to: none
description: A new Flutter project for Mobile Application Developer Position - Technical Assessment .
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  hive: 2.2.3
  hive_generator: 2.0.1
  build_runner: 2.4.11
  hive_flutter: 1.1.0
  path_provider: 2.1.3
  connectivity: 3.0.6
  http: 1.2.1
  cached_network_image: ^3.3.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

